### PR TITLE
S4577563 - MaskRCNN (Task 3)

### PR DESCRIPTION
**Pull request by christianburbon**
This is submission by Christian Burbon for the project task 3 that uses Mask R-CNN to predict lesion segmentation boundaries within dermoscopic images ISIC 2018 Challenge - Task 1: Lesion Boundary Segmentation . The Mask R-CNN model will be trained with the goal of achieving an Intersection over Union (IoU) score of 0.8 for the predicted image segmentation. Training is done using a Nvidia GeForce GTX 1050 Ti (4GB) GPU.

### CODE REVIEW

**Comment by nathasha-naranpanawa** [comment]
- Commit messages are good
- Code is good for normal difficulty
- Performance is good

**Comment by shakes76** [comment]
@christianburbon There are 809 files changed for some reason. This too many to be normal, please check and update, because I can't merge till then (not part of feedback marks but needed for merging your PR). Will try and determine you marks in the meantime.

**Comment by shakes76** [comment]
Actually it is due to the fact you are merging to incorrect branch, please change the destination of the PR to fix, so many files I can't find your work!

**Comment by christianburbon** [comment]
Hi @shakes76, please see https://github.com/shakes76/PatternFlow/pull/259 for the correction. Sorry I got confused in doing the PR.

**Comment by shakes76** [comment]
No worries, closing this one.

**Pull request closed without merging**
