### PR TITLE
45717309 - Van Nhat Huy Nguyen - Knee laterality classification using Perceiver

### PR DESCRIPTION
**Pull request by NhatHuyNguyen**
Hi Shakes & tutors,

This pull request implementation of the Perceiver model on the AKOA knee dataset. My model achieves 94% accuracy on the test set. The pull request consists of:

- `driver.py`: Test driver code of the model.
- `model.py`: Implementation of the model.
- `fourier_encode.py`: Implementation of the Fourier encoding layer.
- `transformer.py`: Implementation of the Transformer layer.
- `cross_attention.py`: Implementation of the cross-attention layer.
- `README.md`: A report of the assignment.
- `imgs`: Additional images provided in the README file.

Please kindly provide a review of this pull request. Any feedbacks would be greatly appreciated. Thank you for your assistance. 

Huy.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
Difficulty Hard

Functionality: OK


Code
- Structure:  OK but shouldn’t transformer.py be part of model.py

README 
- Content: missing references


PR Target OK

General Comments
- Commit messages:  could be a little more descriptive

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No feedback required but can't merge because of merge conflict, please resolve so that I can merge.
Request Description good

**Comment by NhatHuyNguyen** [comment]
Dear Shakes and tutors,

The conflict comes from the .gitignore of another student (idk why that
happened lol). I fixed it  (by deleting that conflicting part).

Cheers,
Huy.

**Comment by NhatHuyNguyen** [comment]
Uh, it happens again today, same file, same student, idk why. Just fixed it, for now.

**Pull request merged**
