### PR TITLE
Improved UNet on ISIC Dataset - Marko Uksanovic[44845090]

### PR DESCRIPTION
**Pull request by Markopteryx**
Name: Marko Uksanovic
Student Number: s4484509

Submitted pull-request for the topic-recognition branch within Patternflow. This requests includes the model and driver code alongside a README explaining the algorithm and how to use the code. The Dice similarity coefficient obtained using the given parameters was 0.857.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Commit messages should be more specific
- Code valid for Easy Difficulty
- Missing quantitative results

Other Feedback
- Please group the `.png` files and put them in a sub-directory
- Please follow python variable naming convections e.g. `Train` -> `train`

**Comment by rexsw** [comment]
Code looks good for easy difficulty

Tensorflow has functions for train test splitting make sure to use the libraries you have before adding more to your project

Code in files such a main_driver should be in a main function

There is no needs for the global constants in model.py, put them in a function next time

Good comments and good use of TensorFlow

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
No quantitative results
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
**Feedback required. Move image files to sub-directory.**
No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by Markopteryx** [comment]
Moved images to sub-directory as suggested in feedback

**Comment by shakes76** [comment]
Links to images broken now in Readme, please update this too

**Comment by Markopteryx** [comment]
Fixed the README, thank you for pointing that out.

**Pull request closed without merging**
