### PR TITLE
OASIS Brain Segmentation with Improved UNet (Dhilan Singh, 44348724)

### PR DESCRIPTION
**Pull request by dylanUQ**
Hey Shakes,

This is my request to contribute to the PatternFlow repository.

I have worked on problem 1 (Segment the OASIS brain data set with an Improved UNet with all labels having a minimum Dice
similarity coefficient of 0.9 on the test set).

My submission includes: 

- A module model.py containing the improved UNet model.
- A driver script unet_improved_oasis_brain.py that trains and evaluates the model.
- And several other modules that are used by the above two modules.

Please refer to my README file for more information. If the images don't show up, please look in the doc_images folder or just run the Jupyter notebook version.

I look forward to your feedback!

Kind Regards,
**Dhilan Singh
44348724**

### CODE REVIEW

**Comment by dylanUQ** [comment]
Fixed up a typo in the README file.

**Comment by dylanUQ** [comment]
Found that using a batch size of 32, would result in an out of memory error during training, somewhat randomly. So reduced down to 12.

**Comment by dylanUQ** [comment]
Everything looks good now. Ready for submission. I look forward to your feedback!
-dylan

**Comment by SiyuLiu0329** [comment]
- Half of the commits were made after deadline
- Code appear valid for Easy Difficulty
- Results appear good 
- Sufficiently detailed commit messages

**Comment by rexsw** [comment]
Code looks good for easy difficulty

For next time;

Try not to have code like leakyReLu = LeakyReLU(alpha=1e-2) floating around put it in a funcation or class

If you're going to have a lot of print functions it's a good idea to have some way to turn them off

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Pull request merged**
