### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by OjasChaudhari23**
Hello Shakes,
My student number is 46941893. I was on extension because of family emergency and thus had got an extension for a week.
I am sorry for the inconvenience.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
**This is an initial inspection, no action is required at this point**
- readme: formatting could be improved; Also should describe what makes the improved unet different from unet; <ore detailed usage for your code would be great, which file(s) should I run to reproduce your results; Dependency missing.
- results: OK
- code: OK, but there seems to be some duplicate files.
- commits: should be more specific
- other comments: please avoid names like *untitled0.py*;  Readme assets (images etc) could be grouped into a folder to reduce clutter.

**Comment by OjasChaudhari23** [comment]
Hello siyu,
You can reproduce the results by running the modules.ipynb file. The untitled0.ipynb is a dummy file and was uploaded just to check how the commit and push works. I forgot to remove it later. In code modules is a jupyter notebook file with the running code and in module.py I have constructed the model

**Comment by OjasChaudhari23** [comment]
Sorry for not removing the unnecessary file.

**Comment by SiyuLiu0329** [comment]
@OjasChaudhari23 no worries, you can include these fixes in the update

**Comment by OjasChaudhari23** [comment]
Also in this project the code in the modules.ipynb file has been distributed in 4 py files i.e. dataset, module, train, predict. Am I good to make the changes now?

**Comment by SiyuLiu0329** [comment]
yes, we will accept these changes.

**Comment by OjasChaudhari23** [comment]
Hello Siyu,
I have tried to update README as much as possible.

**Comment by shakes76** [comment]
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate use and implementation
Good spacing and comments
Header blocks missing -1
## Recognition Problem 
Solves problem
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage 
Module present
Commenting
No Data leakage
Difficulty: Easy -10
## Commit Log
Meaningful commit messages, could be more informative -1
Progressive commits used
## Documentation
ReadMe OK, could use more info -2
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description minimal, could be more informative -2
LATE, but extension granted

**Pull request merged**
