### PR TITLE
DCGAN Final submit from S4598165

### PR DESCRIPTION
**Pull request by Bigturtlefly**
Here is my work. I made some mistakes so you will find my commit log is lost. But you will find my explanation in my last commit.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Sufficiently detailed commit messages according to your PNG files. Please upload a copy to this thread as a reference.
- Code valid for Hard Difficulty
- Results are good


Other Feedback
- Please follow python file  and folder naming convention e.g. `lorem_ipsum_123_abc.py`
- Please group the `.png` files and put them in a sub-directory
- Please do not commit weights or checkpoints 
- (OPTIONAL) Would put main logic in `if __name__ == '__main__'` for the sake of following python convention.
- use "``` ... ```" to format code in readme

**Comment by rexsw** [comment]
Code looks good for hard difficulty

For next time;

Your pull request should have a description of what it is and why it should be merged 

Tensorflow has functions for image resizing and more so there’s no need to also use PIL in your project. 

Make sure you clean up any leftovers when you switch from .ipy to .py i.e #In[4]

Comments such as 
    # turn off axis
     pyplot.axis('off')
Add nothing to the readability of the code and should be avoided. Overall code needs more meaningful comments

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design 
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
Meaningful commit messages 
Progressive commits not verifiable.
** Please link to your repository used either here or invite me to the project if private. You will not recieve a mark until this is done **
## Documentation
Description good
Comments not done properly
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
**Feedback required.**
** Please link to your repository used either here or invite me to the project if private. You will not recieve a mark until this is done **
No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by Bigturtlefly** [comment]
I have invited you to my project. Please take a look. Cheers.

**Comment by Bigturtlefly** [comment]
> ## TF Usage
> OK
> 
> ## Good Practice (Design/Commenting)
> Good design
> 
> ## Algorithm
> Driver Script present
> Shows Usage & Demo & Visualisation & Data usage, Readme OK
> Module present
> 
> ## Commit Log
> Meaningful commit messages
> Progressive commits not verifiable.
> **Please link to your repository used either here or invite me to the project if private. You will not recieve a mark until this is done**
> 
> ## Documentation
> Description good
> Comments not done properly
> Markdown used PDF NOT submitted
> 
> ## Pull Request
> Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch)
> **Feedback required. Submit PDF**
> **Please link to your repository used either here or invite me to the project if private. You will not recieve a mark until this is done**
> No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

I have invited you to my project. Please take a look. Cheers.

**Comment by shakes76** [comment]
Confirmed commit log through private repo thanks

**Comment by shakes76** [comment]
Can you submit the PDF of the Readme please?

**Comment by Bigturtlefly** [comment]
> Can you submit the PDF of the Readme please?

Sorry. I just found that I didn't submit my README successful last time. Maybe there was a technology issue.I submited again. Thanks!

**Comment by shakes76** [comment]
To be consistent with other students, please move image files into their own sub directory before I can merge. Thanks

**Comment by Bigturtlefly** [comment]
> To be consistent with other students, please move image files into their own sub directory before I can merge. Thanks

All the images have been moved to their own sub directory.

**Pull request merged**
