### PR TITLE
Topic recognition - 45616738

### PR DESCRIPTION
**Pull request by A-Bayusuto**
Name: Alexander Bayusuto Wanengkirtyo
Student ID: 45616738

Task 1: Segment the OASIS brain data set with an Improved UNet

Driver with accompanying Models_and_functions file inside the “solution” folder. Images of predictions vs test data inside Driver and “images” folder. README done inside recognition folder.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Commit messages should be more specific, it is good to know you have achieved good DSC, but commit message should mostly be about changes in code.
- Did not follow prescribed project structure. All your content should be in a FOLDER in directory `recognition`
- Code valid for Easy Difficulty
- Results are good

Other Feedback
- Please follow python file  and folder naming convention e.g. `lorem_ipsum_123_abc.py`

**Comment by rexsw** [comment]
Code looks good for easy difficulty

For next time;

Code in files like driver scripts should be in a main function and in a python file.

Paths such as 'H:\\Documents\\COMP3710\\keras_png_slices_data\\keras_png_slices_data\\keras_png_slices_validate\\*.png' won’t work for the user and should either be set dynamical or it needs to be made clear to the user that they need to change these paths

Make sure you remove unused imports

Remember that each file needs to import the libraries it needs functions like decode_img wouldn't work in driver.ipynb because they're not imported correctly

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design, little use of markdown in notebooks
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments OK
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
**Feedback required. Create your own folder for your solution and Readme, All files should be in there and you should not overwrite readme.**
**Add more comments to driver. Notebooks have markdown sections for you to explain what's going on, so you should make use of it.**
No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by A-Bayusuto** [comment]
Feedback response:
- Moved files to new 45616738 OASIS-UNET folder and put back old README.md
- Added more comments to driver using notebook's markdown

**Pull request merged**
