### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by Wen-Hao-18**
Name: Wang Wenhao
Student Number: 46039941
Classify laterality of the OAI AKOA knee data set having the accuracy of 0.98 on the test set with CNN.
The module is in (https://github.com/Wen-Hao-18/PatternFlow/tree/topic-recognition/recognition/Wenhao-AKOA) which get the knee data and classify the left or right
There are two .py main.py(store the parameters and show the result of class and the prediction), model.py(store the model structure)

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Commit messages could be more descriptive
- Code checks out for easy difficulty
- Results appear good

Other Feedback
- Group the `*.png` files and put them in a subfolder
- Instead of 2 class + softmax, I'd use 1 class + sigmoid

**Comment by Wen-Hao-18** [comment]
So, should I need to adjust my file or these are just advice?

**Comment by rexsw** [comment]
The comments from tutors are just feedback you would need to make changes if shakes asks from them.

Code looks good for easy difficulty

Comments such as:
       # relu layer
        relu1 = layers.LeakyReLU(alpha=0.3)(bn1)
And
    # predict and show the precision and recall
    def predict(model):
Don’t add to the readability of the code and you’re better off leaving them out

Places that do need comments are a little lacking in them for example the function  def constructModel(self): could use comments explaining which part of the model is being built when so if you need to debug a part of the model it's easier to know where to look

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
OK commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
**Feedback required. Improve folder structure as suggested by Tutor**
In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by Wen-Hao-18** [comment]
Is that right?

**Comment by rexsw** [comment]
You could have done it all in one commit but yes that is right

**Pull request merged**
