### PR TITLE
Improved Unet model

### PR DESCRIPTION
**Pull request by Zacccc0603**
Hi Shakes and the team,

I would like to create a pull request for my project, my project aims to segment the ISICs data set with the Improved Unet with all labels having a minimum Dice similarity coefficient of 0.8 on the test set.

My project includes file as follows:
data_processing.py  # preprocessing data including split, shuffle, map
dice.py # compute dice coefficient, average coefficient and dice loss
plots.py #predict and plot prediction
Unet_model.py # build a Unet model
main.py # driver script wo run the whole process
README.MD # introduce the project and interpret

Looking forward your feedback.

Thank you,

Yushan Zeng

### CODE REVIEW

**Comment by wooboyeong** [comment]
Code
* NOT improved UNET (implemented vanilla UNET)
* You were supposed to implement "Improved UNET" (by Isensee et al) referenced in the Report Task Sheet - please read the Task Sheet carefully
* Improved UNET has extra residual connections which you did not implement

README
* Wrong reference for improved UNET
* README is messy - we don't need all the epoch history
* Present the results using a plot/graph

General Comments
* Commit messages OK
* Pull request OK

**Comment by Zacccc0603** [comment]
Sorry, but can I get any partial marks in the code section? I'm worried about this, thank you.

**Comment by Zacccc0603** [comment]
And do I still have chance to update my module to get marks? Thank you.

**Comment by wooboyeong** [comment]
You will still get marks since you made PR before the deadline. Also note that you can earn a couple of marks by incorporating feedback into the pull request, as outlined in the Task Sheet.

**Comment by Zacccc0603** [comment]
Hello, 

I have updated my Improved UNet model. Please review the files. Thank you.

**Comment by shakes76** [comment]
## TF/Torch Usage
Incorrect model implemented bu due date (see comments above) -5
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage
Difficulty: Easy -10
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
OK Description and some Comments -3
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Code and model updated after due date, but will be accepted for feedback marks since the PR can be merged.
Request Description OK

**Pull request merged**
