### PR TITLE
s4696541 - Alzheimers Identification using Vision Transformers (ViT)

### PR DESCRIPTION
**Pull request by Minirobbo**
Hi,
This is my pull request for my implementation of using a Vision Transformer to classify Alzheimer's in brain MRIs.
My model was able to achieve ~70% accuracy on the test data from the ADNI Alzheimers dataset.

The pull request contains the following files:
* ```README.md``` - A read-me file containing information on the model and the process of its creation.
* ```dataset.py``` - Python file responsible for dataset creation and access, aswell as creating patches out of images.
* ```modules.py``` - Python file responsible for the entire model architecture.
* ```predict.py``` - Python file that loads a model and prints results when testing it against the test dataset.
* ```train.py``` - Python file used to train the model, saving the model to a file and creating accuracy and loss graphs.
* ```images/``` - Folder containing images for use in ```README.md```

Looking forward to hearing your feedback,
Isaac Robinson

### CODE REVIEW

**Comment by LinfengLiu98** [comment]
Great work.

Model design: Great
Data split: Correct
README: Clearly explained
Commit logs: Great

**Comment by Minirobbo** [comment]
@LinfengLiu98 This was added in the `predict.py` file. Is this sufficient?

**Comment by LinfengLiu98** [comment]
> @LinfengLiu98 This was added in the `predict.py` file. Is this sufficient?

Yes, then that's all good. :)

**Comment by shakes76** [comment]
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate use and implementation
Good spacing and comments
Header blocks
## Recognition Problem 
Solves problem -1 (performance a little low)
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage 
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
ReadMe acceptable/good
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description good

**Pull request merged**
