### PR TITLE
45616756 - GCN on Facebook dataset

### PR DESCRIPTION
**Pull request by wildanazz**
Hello, this is my submission for the report assignment. In this report, I use GCN for node classification on Facebook Large Page-Page Network. There are three main files: driver.py, model.py, and plot.py. Data preparation, model creation, and training is in the driver.py. GCN layer and model class are in model.py. The plots are generated from plot.py. Thank you.

Muhammad Wildan Aziz, 45616756

### CODE REVIEW

**Comment by gayanku** [comment]
- PR Nov 1
- Commits span 3 days ( 30,31,1)
- Non descriptive commit messages.
- Readme is well done with background, results, diagrams.
- multi layer (2) layer GCN, Good _val_ accuracy (+85%) though test accuracy not seem to be provided, it can be expected to be similar. Semi supervised split.
- **Valid for NORMAL ( subject to no TSNE plot or code for plotting submitted)**

- Code does not plot a TSNE as needed. While you are saving TSNE embeddings ( which a 2 dimensional) there is no plot code to plot the node (x,y) on a visualizable graph. This is a requirement. 
- Code structure is ok ( has model file, driver file), but can be improved.  Move pre processing, train etc from main() as you have done when calling tsne() from main rather than have a huge monolithic main().

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage 
Difficulty: Normal -5
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and more Comments could've been used -1
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Please remove model files, these will clog up the repository. Your pull request will not be merged until they are removed. Feedback marks will be awarded when these are removed. -2
Request Description could be more informative -1

**Comment by wildanazz** [comment]
Hi Shakes, I've attempted to remove the unnecessary files that may clog up the repository. Thank you

**Comment by wildanazz** [comment]
Hi @shakes76, I've attempted to remove the unnecessary files that may clog up the repository. Thank you

**Comment by shakes76** [comment]
Feedback marks awarded.

**Pull request merged**
