### PR TITLE
S4548833 YOLOv3

### PR DESCRIPTION
**Pull request by glenyue**

### CODE REVIEW

**Comment by nathasha-naranpanawa** [comment]
- Please remember to provide a detailed pull request comment
- Code is okay for normal difficulty
- Performance is poor
- Commit messages can be more specific

Other notes
- The described model architecture is of YOLOv1 while the used architecture is YOLOv3.
- Provide loss and accuracy graphs to better explain the model's performance
- How were the ground truth annotations preprocessed to be converted into YOLO format? Using LabelImg to annotate bounding boxes is not acceptable.

**Comment by glenyue** [comment]
using the YOLOv3 with darknet 53 to detect lesions within the ISICs data set. After accepting the feedback, I change the description of YOLOv1 to YOLOv3 in the readme file and upload the labelling function

**Comment by glenyue** [comment]
Thanking you for the feedback, I have changed the description of YOLOv1 to
YOLOv3 and added a more detailed pull request comment. I also add a label
function to convert the ground truth into YOLO format

Nathasha Naranpanawa ***@***.***> 于2021年11月16日周二 下午12:39写道：

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage
Difficulty: Normal -5
## Commit Log
Meaningful commit messages, could be more descriptive -1
Progressive commits used
## Documentation
Good Description and more Comments could be added -1
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No feedback required
Request Description missing -2

**Comment by shakes76** [comment]
Can't identify you @glenyue please provide ID or something for me to enter the grade. :)

**Comment by glenyue** [comment]
My student id is s4548833. sorry I did not mention that

Shakes ***@***.***> 于2021年11月21日周日 下午4:57写道：

**Comment by glenyue** [comment]
May I ask about my difficult grade, the YOLO should be normal and mine is
easy.
Thank you

明月 ***@***.***> 于2021年11月21日周日 下午7:46写道：

**Comment by shakes76** [comment]
Thanks. Also Updated to Normal difficulty

**Pull request merged**
