### PR TITLE
s4524825 Project Pull Request

### PR DESCRIPTION
**Pull request by djamahl99**
The pull request submitted is a Perceiver implementation used to classify the laterality of the AKOA knee dataset.

The project provides files for training, evaluating and testing the model. 

- split the data with generate_labels.py and then 
- train the model using train.py and then
- evaluate classification using driver.py to evaluate a classification

Please read README.md for more information on the model and the classification task.

### CODE REVIEW

**Comment by djamahl99** [comment]
I realized I started on master so rebased my changes onto topic-recognition hence the other commits

**Comment by SiyuLiu0329** [comment]
Difficulty Hard

Functionality: OK

Code
- Structure:  OK 
- .py files should be lowercase


README 
- Content: missing below
- Missing references
- A perceiver diagram would be nice
- You should link your plots in your read me
- Dependencies?
- Usage?


PR Target OK

General Comments
- Commit messages:  OK
- Please put png files in a separate folder

**Comment by SiyuLiu0329** [comment]
Difficulty Hard

Functionality: OK

Code
- Structure:  OK 
- Code cleanup recommended (unused comments in some files)


README 
- Content: missing references at the end
- Dependencies?


PR Target OK

General Comments
- Commit messages:  OK
- What file did you edit in https://github.com/djamahl99/PatternFlow/tree/topic-recognition/algorithms 
- Please do not commit weights
- Please do not commit *_.png, same with *_.csv
- Please put pngs in a separate folder
- Please do not upload logs / results as files. You just need to report them in readme
- These are MRIs btw not X-rays

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage 
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description but could have examples and network achitecture and Comments -1
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Please remove model files, these will clog up the repository. Your pull request will not be merged until they are removed. Feedback marks will be awarded when these are removed. -2
Request Description could be more informative -1

**Comment by djamahl99** [comment]
I have responded to the provided feedback. 

Changes made:
- images have been moved to a separate directory 
- have added example images
- model architecture image added to README
- removed .csv, .h5, .txt, and .png (model files, split files, training files, data files)
- moved header blocks up as were below imports and must have been missed
- copied references over to README
- updated pull request description to be more informative

**Comment by shakes76** [comment]
Feedback marks awarded.

**Pull request merged**
