### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by ChaoticCooties**
Hello,

Unfortunately, I wasn't able to acquire the ADNI dataset in time hence I've used MNIST instead. 
This PR involves my implementation of a Perceiver transformer with >90% accuracy on the MNIST dataset.

Aside from that, everything should be accounted for. If there are any other issues, please let me know.

Cheers,
Chegne Eu Joe
No. 46172923

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
Difficulty Hard

Functionality: OK but trained on MNIST instead of OA or ADNI


Code
- Structure:  OK 

README 
- Content: _
- Please also add reference for the guides / code you have followed (if any)
- You should have a description of the data as well. What data are we dealing with, how are they processed, how do they go into the model?
- What does the acc plot represent? Is it training or testing? What is the train / val / test split?


PR Target OK

General Comments
- Commit messages:  OK

**Comment by ChaoticCooties** [comment]
Hello,

Thanks for looking at my PR. I've noted your feedback and have updated my README with a new commit.
Please check and let me know if there are any other issues.

Thanks!

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation, but not possible to verify accuracy, plot has not scales and no values provided -5
## Good Practice (Design/Commenting)
Good spacing and comments
Some Header blocks missing -1
## Algorithm 
Driver Script present but solves for easier dataset, a standard one -5
Shows Usage & Demo & Visualisation & Data usage 
Module present
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description could be more descriptive -1

**Comment by ChaoticCooties** [comment]
Hi Shakes,

Apologies for the extra comment here but could you please clarify what did you meant by this:
> Adequate use and implementation, but not possible to verify accuracy, plot has not scales and no values provided -5

From what I see, I have plotted the epochs and accuracy accordingly. I suspect that this may be an issue with the dark theme of GIthub itself since my plot scales have a transparent background and hence hidden.

Picture for reference:
image

Thanks!

**Comment by shakes76** [comment]
Thanks for pointing this out, it is indeed caused by dark theme, although it still uses MNIST data.
Mark Amendment:
Adequate use and implementation

**Pull request merged**
