### PR TITLE
s4528612-OAI-AKOA-knee-data-Perceiver 

### PR DESCRIPTION
**Pull request by Majurran**
Hi COMP3710 Team
This is my implementation of the Perceiver achieving a maximum test accuracy of 99.6% on a test set containing 4% of the data. 
The files included are the README.md file, the driver.py file which runs the script, the model.py file which contains the perceiver classes and functions, and the images folder which contains images used in the README file.
Thank you
Majurran - 45286122

### CODE REVIEW

**Comment by Majurran** [comment]
I just noticed when I tried to move my main function I copied my main function instead so now I have two. Hopefully that doesn't throw an error, but it can be rectified by deleting either one.

**Comment by SiyuLiu0329** [comment]
Difficulty Hard

Functionality: OK

Code
- Structure:  OK 
- Main could use more comments

README 
- Content: OKI

PR Target OK

General Comments
- Commit messages:  OK

**Comment by Majurran** [comment]
More Comments were added incorporating the feedback given.

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description OK

**Pull request merged**
