### PR TITLE
ISIC data segmentation using UNet

### PR DESCRIPTION
**Pull request by izzygpeters**
Name: Isabel Peters
Student number: 45371756
Code for my algorithm which segments the ISIC data using the UNet architecture.

### CODE REVIEW

**Comment by izzygpeters** [comment]
08/11 UPDATE: Deleted redundant commented code from metrics.py and small changes to README.md (which are not reflected in my Turnitin pdf submission from yesterday - sorry).

**Comment by SiyuLiu0329** [comment]
- Code valid for Easy Difficulty
- Sufficiently detailed commit messages
- Results are good

Other Feedback 
- Good overall. I would put main logic in `if __name__ == '__main__'`

**Comment by rexsw** [comment]
Code looks good for easy difficulty

For next time;

Comments such as 
# Shuffle datasets
    train_ds = train_ds.shuffle
Add nothing to the readability of the code and should be avoided. Overall comments were well done

Paths such as 'H:\\COMP3710\\PatternFlow\\recognition\\ISIC_UNET' won’t work for the user and should either be set dynamical or it needs to be made clear to the user that they need to change these paths

Code is terrifyingly well laid out

**Comment by shakes76** [comment]
## TF Usage
Good
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Pull request merged**
