### PR TITLE
s4433723 AKOA Perceiver Transformer

### PR DESCRIPTION
**Pull request by JoeHolownia**
My implementation of the AKOA Perceiver Transformer to classify knee laterality.

Contains:
- a driver.py file: which sorts the input AKOA dataset into datasets, runs the algorithm to train the model and produces output.
- a model.py file which contains all logic for the perceiver achitecture constructed for the task.
- a README.md file which describes the project and how to use the files.
- several image files used in the README file and for descriptive purposes of the model architecture, training data etc.

### CODE REVIEW

**Review by JoeHolownia — COMMENTED** [review]
This request adds the desired functionality to the patternflow repo, and is documented with a README file and image files to support understanding of the model.

**Comment by JoeHolownia** [comment]
The driver.py may get stopped mid-way through running due to a plt.show() from matplotlib of the input training data. By dismissing the window, the algorithm continues to run.

**Comment by SiyuLiu0329** [comment]
Difficulty Hard

Functionality: OK

Code
- Structure:  OK 


README 
- Content: OK

PR Target OK

General Comments
- Commit messages:  OK
- Please put png files in a separate folder

**Comment by JoeHolownia** [comment]
I have updated this pull request based on the feedback. Images are now located in a separate directory.

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
Header blocks
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description good

**Pull request merged**
