### PR TITLE
Topic recognition - Improved UNet on ISIC data

### PR DESCRIPTION
**Pull request by MujiDipto**
Hi Shakes and the teaching team,

I have completed the Task 1: Segment the ISICs data set with the Improved UNet using TensorFlow and have achieved around 90% accuracy.

The repo contains the following:
images/  - contains images for the README
data_loader.py  - used for loading and processing data
driver.py  - the main script that creates and trains the model on the processed data
license.txt - license information
model.py  - creates an Improved UNet Model
utilities.py  - contains utility functions for displaying images, calculating DSC etc.

Looking forward to your response.

Kind regards,
Mujibul Islam Dipto
44961374

### CODE REVIEW

**Review by wooboyeong — CHANGES_REQUESTED** [review]
Please remove commit 7a95de4 - not your README

**Comment by wooboyeong** [comment]
README
* Please report average DSC for test set in README

General Comments
* Code OK for EASY
* Commit messages OK

**Comment by MujiDipto** [comment]
Thanks for the suggestions. I have made both changes. Please have a look if all looks good thanks.

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
Header blocks
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage 
Difficulty: Easy -10
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No feedback required
Request Description good

**Pull request merged**
