### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by vniernvhid**
Task 3: Detect lesions within the ISICs data set with the yolo-v3  
s4565705

### CODE REVIEW

**Comment by vniernvhid** [comment]
Task 3: Detect lesions within the ISICs data set with the yolo-v3

**Comment by nathasha-naranpanawa** [comment]
- Commit messages can be more specific
- Code is good for normal difficulty
- Performance is good

**Comment by vniernvhid** [comment]
Thanks for the comment. 
In the next time, I will write more specific commits to help the understanding.

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
Header blocks
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Could have used module for model/functions, all in Notebooks. -1
No Data leakage 
Difficulty: Normal -5
## Commit Log
Meaningful commit messages, could be more descriptive -1
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No feedback required.
Request Description could be more informative -1

**Pull request merged**
