### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by MajorRedux**
Name: Richard Roth
Student Number: s4577741

This is an algorithm that explores the OAI AKOA dataset utilising a DCGAN for incorporation in the recognition area of the COMP3710 PatternFlow project.

The OAI AKOA dataset contains images of the knee MRI slices of Osteoarthritis patients. This data is used in a Deep Convolutional Generative Adversarial Network to train a model that can discriminate an MRI image of a nominal knee from an MRI image of an arthritic knee. 

I'm looking for feedback on the structure of the discriminator and the generator; comments on kernel intialiser, activation functions and loss function used; overall impression of results; and areas of improvement or further research for the algorithm. 

Feedback within the next two weeks would be appreciated.

### CODE REVIEW

**Comment by MajorRedux** [comment]
Added some more details to the README.md and fixed the Gif issue.

Ran a final test with the algorithm using a high optimisation model with good results.

**Comment by SiyuLiu0329** [comment]
- Sufficiently detailed commit messages
- Code valid for Hard Difficulty
- Results not perfect, but are of acceptable quality

Other Feedback
- I would separate the code from model implement and put them in a seperate file.

**Comment by MajorRedux** [comment]
I spent hours trying to get an external file to work with colab and gdrive, but was having massive issues. The original plan was to have all the support code, functions and models in a separate file, but I couldn't get it to work. In the end I gave up and just did it as one big file.

Thanks for the feedback.

**Comment by MajorRedux** [comment]
Shouldn't have closed it.

**Comment by rexsw** [comment]
Code looks good for hard difficulty

For next time;

Code in files like driver scripts should be in a main function and in a python file.

Paths such as "/content/gdrive/My Drive/Colab Notebooks/data/AKOA_Analysis\" won’t work for the user and should either be set dynamical or it needs to be made clear to the user that they need to change these paths

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme sparse
Module NOT present
Results not great but acceptable
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch)

**Pull request merged**
