### PR TITLE
DCGAN on OASIS Brain - Peter Ngo

### PR DESCRIPTION
**Pull request by PeterDinhNgo**
Implemented a DCGAN to generate images of brains from the OASIS Brain dataset.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Work submitted before deadline
- Code appear valid for Hard Difficulty 
- Results are good 
- Sufficiently detailed commit messages for the most part

Other feedback
- Good code structure and modularisation
- You dont actually need @tf.function for the training loop

**Comment by rexsw** [comment]
Code looks good for hard difficulty

For next time;

Comments such as 
      #discriminator loss
    def disc_loss(generated_outputs, real_outputs):
Add nothing to the readability of the code and should be avoided. Overall comments were well done

**Comment by atemt001** [comment]
Hello,
your results looks interesting....I was wondering where I can find White Matter, Gray Matter masks? I went through MRI OASIS Dataset and I haven't seen these masks .. or do I need to request them?.. please Help 

Thank you

**Comment by PeterDinhNgo** [comment]
> Hello,
> your results looks interesting....I was wondering where I can find White Matter, Gray Matter masks? I went through MRI OASIS Dataset and I haven't seen these masks .. or do I need to request them?.. please Help
> 
> Thank you

Hi,
The masks are based on a preprocessed version of the OASIS Brain dataset provided by the COMP3710 teaching team - you can access it here https://cloudstor.aarnet.edu.au/plus/s/n5aZ4XX1WBKp6HZ/download.

**Comment by PeterDinhNgo** [comment]
Student ID: 43944419
Name: Peter Ngo

**Comment by atemt001** [comment]
Thank you and I appreciate your quick response.

**Comment by PeterDinhNgo** [comment]
Glad I could help. If you want more specific details about the preprocessing done, Dr. Shakes Chandra from UQ is the professor.

**Comment by atemt001** [comment]
hello,
I was wondering why you convert your data from nifti to png format? ,,anyway still can use the same data but with original nii format?

**Pull request merged**
