### PR TITLE
GCN on Facebook Large Scale Dataset: 46507422

### PR DESCRIPTION
**Pull request by maryam-m-k**
Hi there, 
This is an initial pull request for the GCN task in the COMP3710 Report. 
Name: Maryam Khan
Student Number: 46507422

### CODE REVIEW

**Comment by gayanku** [comment]
Code and TSNE looks ok, though would be good to have a slightly higher accuracy (>80%)

**Comment by shakes76** [comment]
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate use and implementation
Good spacing and comments
Header blocks missing -1
## Recognition Problem 
Solves problem (slightly lower accuracy) -1
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage 
Module present
Commenting
No Data leakage
Difficulty: Normal -5
## Commit Log
Meaningful commit messages, could be more informative -1
Progressive commits used
## Documentation
ReadMe acceptable
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Feedback required, rename your folders with ID or equivalent, otherwise will conflict with other requests -2
Request Description minimal, could have more info about PR itself -1

**Comment by maryam-m-k** [comment]
Hi- to confirm, the feedback required is improved accuracy on the model, and renaming the folder with student ID?

**Comment by maryam-m-k** [comment]
> "Feedback required, rename your folders with ID or equivalent, otherwise will conflict with other requests -2"

^ This comment has been actioned- GCN source folder renamed to "GCN 46507422". The unused MySolution directory has been removed. Please let me know if further changes are required.

**Pull request merged**
