### PR TITLE
Daniel Ju Lian Wong, 46069340 : Stable Diffusion Model on the OASIS Brain MRI Dataset

### PR DESCRIPTION
**Pull request by DanielJWong**
I was told that it'd be allowed to sneak in one more push / pull in a private EdEx question before monday, so Here it is.

I've implemented a stable diffusion model on the OASIS brain MRI dataset. The model I've implemented is a proper latent model: It doesn't learn the denoising procedure on the full image - it only denoises the image's latent representation to minimise the cost of computation.

To achieve a latent representation of the image space, I've also implemented and trained a convolutional autoencoder, built out of a separate encoder and decoder. The encoder has a downsampling factor of 4.

### CODE REVIEW

**Comment by DanielJWong** [comment]
I've closed my other pull requests to the repo.

Also, half the commit in this are from my other account. I couldn't figure out how to change who git was identifying me as in cmd for a while, so I gave up and invited myself as a collaborator.

**Comment by DanielJWong** [comment]
+ Just to expand on the last commit, there were a few bugs that I accidentally introduced when I pasted my model over from google colab into the .py files. The latest commit involved fixing those bugs (mostly fixing inconsistent var names, import statements, ect). No changes were made to the architecture of the actual models used.

**Comment by SiyuLiu0329** [comment]
**This is an initial inspection, no action is required at this point**
- Readme: OK but package info should contain version numbers
- Results: Acceptable considering the difficulty of the task.
- Code: Good, good coverage of many technical aspects. Models seem to be working for the most part. Minor comment: python filenames should be in snake_case.
- Commit messages: Good

IMPORTANT: Commits are not in the right place. Did you create the topic-recognition branch yourself? You should fork Shakes repo in whole (there is a checkmark when you fork) and commit to his topic-recognition branch. You should be able to see work from the previous years in "recognition folder"

**Comment by DanielJWong** [comment]
> **This is an initial inspection, no action is required at this point**
> 
> * Readme: OK but package info should contain version numbers
> * Results: Acceptable considering the difficulty of the task.
> * Code: Good, good coverage of many technical aspects. Models seem to be working for the most part. Minor comment: python filenames should be in snake_case.
> * Commit messages: Good
> 
> IMPORTANT: Commits are not in the right place. Did you create the topic-recognition branch yourself? You should fork Shakes repo in whole (there is a checkmark when you fork) and commit to his topic-recognition branch. You should be able to see work from the previous years in "recognition folder"

Ah yeah, my bad. I believe after I initially forked, for whatever reason I didn't have topic-recognition as an available branch - only master, so I went created the topic-recognition branch manually. Would merging the contents of the original topic-recognition into my branch be an acceptable fix?

**Comment by shakes76** [comment]
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate use and implementation
Good spacing and comments
Header blocks
## Recognition Problem 
Solves problem (poor performance but difficult task) -1 +1
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage (plots no labelled) -1
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
ReadMe acceptable/good
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description OK, could be more informative -1

**Pull request merged**
