### PR TITLE
Topic recognition GCN 45249435

### PR DESCRIPTION
**Pull request by Pentaflouride**
Implemented a multilayered GCN for task 2 (using the the facebook dataset). The driver.py file runs by simply running the file without any parameters. The output will be the model training, the model getting tested, a graph of the accuracy and loss of the validation data set and a tsne of the embedded data set classified. 
The readme file is as described in the task.
The model.py file has the model wrapped in a function.
The notebook file has more raw outputs which were omitted from the model.py file. Things like shapes and types of data. 
The rest of the files are either images (so they can be added to the readme file) or the data itself (so I can load it in my script).
I've taken inspirations from 2 blog posts. One made by Anton Ruberts and huonw

Name: Paul Turculetu
Student number: 45249435
Course: COMP3710

Kind regards,
Paul

### CODE REVIEW

**Comment by gayanku** [comment]
- Submitted on Oct 27
- Commits' over 3 days (25 to 27)
- Good details in commits and PR. 
- Readme is well done with background, results, diagrams.
- multi layer (3) layer GCN, Good accuracy (+85%), Semi supervised split.
- **Valid for EASY (subject to not implementing own GCN model).**

- You need to implement your own GCN (convolution layers and model) rather than use the GCN imported from stellargraph.layer which is a 3rd party library.
- In future, code structure and modularization can be improved by moving the preprocessing ( and creating normalized Adj) and TSNE visualization outside of the main learning code (train, val and test).  Your use of a single composite function to do everything can be somewhat less flexible for from a code re-sue and maintenance perspective at times. 
- Your diver file is also redundant as it only calls run_model() which contains all your code.

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
Header blocks missing -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module NOT present (all in one function) -1
No Data leakage
Difficulty: Easy -10
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Please remove model files, these will clog up the repository. Your pull request will not be merged until they are removed. Feedback marks will be awarded when these are removed. -2
Request Description OK

**Comment by Pentaflouride** [comment]
Deleted the notebook file since it did not do anything. I cannot delete model.py because driver.py runs model.py. I also cannot get rid of the images because they are used in the README file. The other files are data files.

**Comment by shakes76** [comment]
Data files (and CSV files) should not be in the repository, the .py files are fine. Please remove the data files.

**Comment by shakes76** [comment]
Feedback marks awarded. Still can't merge though because of the .npy file present.

**Comment by Pentaflouride** [comment]
Sorry I forgot one. Should be good now.

**Pull request merged**
