### PR TITLE
s45028818] - Improved UNet on ISIC Data

### PR DESCRIPTION
**Pull request by d7a7**
This model performs image segmentation on the ISIC dataset, this dataset contains images of skin cancer and their respective ground truth mask values, to perform the segmentation of the dataset this is an implementation of the Improved U-Net. 
This pull request contains a model.py file which constructs the model and a driver.py file which calls model.py and trains a model upon data in the data folder. Instructions on how to organise the data is contained within the README.

Would welcome feedback upon the implementation.
Thanks, Douglas

### CODE REVIEW

**Comment by wooboyeong** [comment]
General Comments
* Code OK for EASY
* Commit messages OK
* Documentation OK
* Pull request OK

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
Header blocks
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage 
Difficulty: Easy -10
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Please remove test file in parent directory. This file is not necessary -2
Request Description OK

**Comment by d7a7** [comment]
Modified pull request in response to feedback, the change made was:
- There was a test file accidentally left in the parent directory from when I was setting up the git workflow at the beginning of the assignment, the left over file has been removed.

Please let me know if any further changes are required.
Cheers, Douglas

**Comment by shakes76** [comment]
Feedback marks awarded.

**Pull request merged**
