### PR TITLE
s46331391: Improved UNet

### PR DESCRIPTION
**Pull request by wakameds**
ID: s46331391
Task: Improved UNet

The pull request includes the seven files
- README.md
- criterion.py
- dataloader.py
- driver.py
- model.py
- model_train_val.py
- visualise.py

README.md provides a brief explanation about the model structure, model evaluation with dice coefficient, dice loss, and image segmentation. The dice coefficient of the test images shows over 0.87.

### CODE REVIEW

**Review by wooboyeong — CHANGES_REQUESTED** [review]
Please remove commit 02e5662 - not your README

**Comment by wooboyeong** [comment]
General Comments
* Commit messages OK mostly but could be more descriptive
* Code OK for EASY
* Documentation OK

**Comment by wakameds** [comment]
Removed commit 02e5662

**Comment by wakameds** [comment]
Hi Professor. I think the conflict problem happened due to a response to remove a commit log request. If possible, would you tell me what I should do to solve the problem?

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
Header blocks
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage 
Difficulty: Easy -10
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch)
Still need to fix the merge conflict before I can merge -2
Request Description OK

**Comment by wakameds** [comment]
Hi, Professor Shakes. I fixed the merge conflict. Please confirm it.

**Comment by shakes76** [comment]
Feedback marks awarded.

**Pull request merged**
