### PR TITLE
CSIRO 3D Prostate UNET Application

### PR DESCRIPTION
**Pull request by s4581614**
Added code is located at recognition\ProstateUNET3D_45816145.

See readme in the subfolder to see how to run and debug application. The driver.py file shows UNET background, how to run it for yourself, and the performance of the algorithm on the CSIRO 3D Prostate dataset.

Code is neatly composed in a hierarchical, DOP manner.

### CODE REVIEW

**Review by wooboyeong — CHANGES_REQUESTED** [review]
Please undo changes made to someone else's file - commit 9963904

**Comment by wooboyeong** [comment]
Code
* Poor segmentation performance for rectum and prostate
* Batch normalisation may help
* Might need to train for longer
* For image normalisation, might be better to use maximum for each image rather than a fixed value

README
* Please show example outputs in README

General Comments
* Commit messages OK

**Comment by s4581614** [comment]
Apologies, I am not sure how that happened, as I did not touch other contributor's files manually.

Issue is now fixed though :) Reverted the readme using `checkout 9963904~1`.

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present, though has some poor performance -2
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage
Difficulty: Normal -5
## Commit Log
Meaningful commit messages
Progressive commits used
## Documentation
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No feedback required
Request Description could be more informative -1

**Pull request merged**
