### PR TITLE
StyleGan1_Xinqian Wang_S4565489

### PR DESCRIPTION
**Pull request by Wangxinqian**
Hi, Dr. Shakes (and COMP3710 team),

I implemented a StyleGan and generate images using OASIS Brain Dataset. The code has mainly used the [repositories](https://github.com/rosinality/style-based-gan-pytorch) for reference. The code is written in Google Colab and reformatted into several Python files, the general explanation is as below:

- **requirements.txt** -> Some packages need to be installed before running.
- **model.py** -> StyleGan's Generator and Discriminator.
- **make_imdb.py** -> Prepare the Imbd dataset.
- **train.py** -> Training the StyleGan. It will save the model and generate image samples from time to time.
- **test.py** -> Generate images with mean style.
- **StyleGANipynb.ipynb** -> The main file I operate on most of the time.
- **StyleGANipynb_Colaboratory.pdf** -> **StyleGANipynb.ipynb**'s pdf version.
- **image[folder]** -> All images used during writing the ReadMe file.

Best Regards,
Xinqian Wang
Student ID: 45654897

### CODE REVIEW

**Comment by Wangxinqian** [comment]
> Hi, This is the first time for me to make a pull request. So far, I have only written some comments for the trials in ReadMe. What I mainly did is just simulate the trial from the StyleGAN1 paper's Chapter-3 (Properties of the style-based generator). Additionally, at first, I m curious about how the mapping network disentangled the latent code and use some plots to learn. I'm reaching the StyleGAN1 paper's Chapter-4, I think it may give me more information about the mapping network.

**Comment by Wangxinqian** [comment]
> Hi, This is the first time for me to make a pull request. So far, I have only written some comments for the trials in ReadMe. What I mainly did is just simulate the trial from the StyleGAN1 paper's Chapter-3 (Properties of the style-based generator). Additionally, at first, I m curious about how the mapping network disentangled the latent code and use some plots to learn. I'm reaching the StyleGAN1 paper's Chapter-4, I think it may give me more information about the mapping network.

???Quote Reply Test

**Comment by Wangxinqian** [comment]
Reopen and Comment

**Comment by Wangxinqian** [comment]
I uploaded one image for the truncation method, during the due date 16:00, I hope it is not too late.

**Review by WeiDaiwow — COMMENTED** [review]
PRO:
Have both test and driver file
Nice readme file
An algorithm solves the problems
Good design and nice implementation
Nice comments
Correct pull request with the description
nice visualization and plots
Dependencies included
Nice output and plots
Nice Markdown
Nice reference
Great code with very nice structure

Excellent analysis for the results (both latent disentanglement and style mixing)

CON:
All code committed in a single day
Not enough description and explanation of the chosen algorithm in the readme file (lots of references tho)
No dependencies

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
Header blocks
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present 
No Data leakage
Difficulty: Hard
Very good analysis +2
## Commit Log
Meaningful commit messages, but could be more descriptive, Progressive commits used though done in a single day -1
## Documentation
Good Description and but more comments could be present in the code -1
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch)
No feedback required
Request Description good

**Pull request merged**
