### PR TITLE
Topic recognition - Dylan Baynes (45822801)

### PR DESCRIPTION
**Pull request by Quantum-Kitten**
Final version of my improved unet classification task, can run the train.py file and it will execute and eventually produce nice output graphs to see how well the segmentation went.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
**This is an initial inspection, no action is required at this point**
- Code: seem OK
- Results: im unable to verify the results since there are no plots, visualisation or quantitative reporting.
- Readme: should include a description of improve unet, what makes it novel etc; should include test set results; should include input and output visualisation; missing references; dependencies should include version 
- Commit Messages: should be more specific
- Other comments: N/A

**Comment by shakes76** [comment]
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate use and implementation
Good spacing and comments
Header blocks missing -1
## Recognition Problem 
Solves problem (no results or plots) -4
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage 
Module present
Commenting
No Data leakage
Difficulty: Easy -10
## Commit Log
Meaningful commit messages (more details in commit msgs) -1
Progressive commits used
## Documentation
ReadMe minimal, needs more info and intro -2
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Feedback required, fix conflicts and changes to other student works. -2
Request Description minimal, need more info -1

**Comment by Quantum-Kitten** [comment]
Based on the current commits I believe i've fixed the issues and it should be good to do with a merge, had a really confusing time with this since I never touched these files in the first place and I undid the only commit that had these folders modified in the first place and I still apparently had issues? Either way I hope this is correct after these 5 new commits. Sorry about it this, github really not being nice to me on this project

**Comment by Quantum-Kitten** [comment]
Final Pull Request Comment: fixed conflicts with the main README file as well as accidental modifications to other students files to due merging from an outdated commit to the topic-recongnition branch.

The pull request is for an implementation of the improved UNET segementation of the ISIC dataset. This aims to generate masks for identifying unique elements within the image, specifically the skin lesions of the ISIC database which this is designed from. This was implemented for Semester 2 2022 by Dylan Baynes

This directory does not contain the required files in order to not be including the 8gb~ of images so in order to properly test this a Data file needs to be created onto the local directory version of this folder and the 2018 ISIC images inserted into this folder

**Comment by shakes76** [comment]
Feedback marks will be awarded. Merging can't be done though until tf events file in log folder is removed.

**Pull request merged**
