### PR TITLE
Topic recognition-Updated

### PR DESCRIPTION
**Pull request by lyubinapple**
Dear Dr Chandra,

Here is the COMP3710 report pull request.
My name is Bin Lyu. (ID: 45740165)
Task: Problem 6. DCGAN on OAI AKOA dataset.
Please kindly refer to the codes and report.
Look forward to your feedback.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Sufficiently detailed commit messages
- Shakes commits should not have appeared in your branch
- Why have you got segmentation results in a DCGAN project. Where are the code for the segmentation results?
- Code appear valid for DCGAN (Hard) but the segmentation work require clarification 
- Results are good

Other Feedback
- Please follow python file naming convention e.g. `lorem_ipsum_123_abc.py`

**Comment by lyubinapple** [comment]
Hi Siyu,

Thank you for you feedback!
The segmentation result is my work at beginning. Then I do the DCGAN. Daiwei told me that one person just can upload one task’s code and other attempts can be shown as appendix in readme. So I just keep the DCGAN code and show the result of my 3D Unet in appendix.

Best regards
Bin

**Comment by rexsw** [comment]
Code looks good for hard difficulty

Comments such as 
       # define subplot
        pyplot.subplot(n, n, 1 + i)
Do not add to the readability of the code and should not be included. But overall good comments

Code in files like DCGAN_OAI should be in a main function

Tensorflow has functions for reading and resizing images so you don’t need to use and extra library like PIL

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Partially Successful Pull Request (Working Algorithm Delivered on Time but incorrect Branch) 
**Feedback required. Please move your work to topic-recognition branch and not master.**
No Proper Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by lyubinapple** [comment]
According to the feedback from Shakes, I do the pull request again from master to topic-recognition. Sorry for the wrong branch at first time.

Author
Bin Lyu (45740165)

Problem
Use DCGAN to develop a generative model of the OAI AKOA knee dataset to create reasonably clear image.

Included Files
Includes a file for the model of the DCGAN and a driver script to run training/testing on the OAI AKOA dataset. Also includes 6 png images in folder “resource” and a README file for documentation.
Model_DCGAN.py is the model file and DCGAN_OAI.py is the driver script. The driver script can be ran using an IDE or with the command line, assuming all dependencies have been installed as per the README.

For more information, please see the README

**Comment by shakes76** [comment]
A number of files in my InfoVAE project are still being overwritten, perhaps update your topic-recognition branch

**Comment by lyubinapple** [comment]
I deleted your InfoVAE and recognition/README.md on my branch before. That's maybe the reason why overwritten happens. I just re-uploaded those files. The folder and content should now match yours. But now the branch conflicts happen. I do not have write access to recognition/README.md(which file was deleted by me before pull request and upload now). It shows that only those with write access to this repository can merge pull requests. I can not resolve conflicts (resolve conflicts button disable)
Sorry for the inconvenience but would you please tell me what can I do now?

**Comment by lyubinapple** [comment]
Comment add: Now readme file in recognition folder is exactly your original one. I just upload it to where it should be. So I don't know how to fix this conflict. Look forward to your help.

**Comment by shakes76** [comment]
You can try updating your branch and then reverting the files in question.

**Comment by lyubinapple** [comment]
Dear Dr Chandra,
Sorry to bother you again. I have fix the conflict. 
Would you please merge my branch?
Besides, can I get the feedback 2 marks as well?
Thank you for your teaching and help this semester.

**Pull request merged**
