### PR TITLE
Topic recognition - UNET with ISIC dataset 

### PR DESCRIPTION
**Pull request by arushi-mah**
Hi Shakes,

Please accept the pull request for the completed report for COMP3710.
This is my submission for Problem 3 : Implementing UNet using ISIC dataset.

The folder contains implementation of UNET on ISIC dataset which contains of ISIC_dataset_with_UNET.py file, Test_driver_script.py file, Readme.md file and relevant images. 
The Overall dice coefficient obtained for this problem was 0.887. 

Any suggestions will be highly appreciated.

Arushi Mahajan
45755833

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Commit messages should be a bit more specific
- Code valid for Easy Difficulty
- Results are good 

Other Feedback
- Please follow python file  and folder naming convention e.g. `lorem_ipsum_123_abc.py`
- Please group the `.png` files and put them in a sub-directory

**Comment by rexsw** [comment]
Code looks good for normal difficulty

For next time;

Tensorflow has functions for image resizing and train_test splitting so there’s no need to also use skimage and sklearn in your project 

Comments such as 
    # train-validation-test split
    def split_datatset(X_isic_train, y_isic_train):
Add nothing to the readability of the code and should be avoided. But overall comments are good.

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
**Feedback required. Move images files into sub-directory.**
No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by arushi-mah** [comment]
Hi Shakes, 

I have made the necessary changes as suggested; created a new sub-directory 'Images' and pushed all the images to the folder and changed the Readme.md file accordingly. 

Arushi Mahajan
45755833

**Pull request merged**
