### PR TITLE
s4361465 Kelsey McGahan 

### PR DESCRIPTION
**Pull request by yeksel**
Knee Laterality Classification Project for COMP3710.

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Work submitted before due
- Sufficiently detailed commit messages 
- Code valid for Easy Difficulty 
- Results are good

Other Feedback 
- Good work. Place items to be ignored in the .gitignore located in the project's root directory.

**Comment by rexsw** [comment]
Code looks good for easy difficulty

For next time;

Code in files like driver scripts should be in a main function and in a python file.

Your pull request should have a description of what it is and why it should be merged 

Tensorflow has functions for image resizing and more so there’s no need to also use cv2 in your project. Same for sklearn and train/test splitting 

Make sure you remove unused imports

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK
Module present
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by yeksel** [comment]
Just submitted the README pdf to Blackboard. I thought I had submitted it when I did the pull request. Thank you!

**Pull request merged**
