### PR TITLE
Topic recognition

### PR DESCRIPTION
**Pull request by 1665446266**
Project 2 :  Classify laterality (left or right sided knee) of the OAI AKOA knee data set.
Xiaomeng Cai
45490826

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
- Commit messages should be more specific
- Code valid for Easy Difficulty
- Good results

Other Feedback
- Could simplify the project structure. It is a little hard to navigate.

**Comment by rexsw** [comment]
Code looks good for easy difficulty

For next time;

There’s no need to have so many folders and readmes, it makes it harder to understand the whole project. 

Your pull request should have a description of what it is and why it should be merged 

Paths such as 'E:\COMP3710DATA\dataset\validation' won’t work for the user and should either be set dynamical or it needs to be made clear to the user that they need to change these paths

Comments such as 
     # load model       
     new_model = tf.keras.models.load_model('trained_model.h5')
Add nothing to the readability of the code and should be avoided. Overall comments were well done

Make sure you remove unused imports

**Comment by shakes76** [comment]
## TF Usage
OK
## Good Practice (Design/Commenting)
Good design and comments
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage, Readme OK (but doesn't need to be scattered in each folder)
Module present
## Commit Log
Meaningful commit messages 
Progressive commits used 
## Documentation
Description and Comments good
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Request Description. In the future, a more detailed pull request could've been done. When developer receiving the request is not known, the request could be rejected. Remember you could use/reuse the README info.

**Comment by shakes76** [comment]
You should avoid brackets and spaces in file names when coding.

**Pull request merged**
