### PR TITLE
VQVAE Algorithm [Task 8] - (Conal O'Leary s4583653)

### PR DESCRIPTION
**Pull request by scooobs**
# OASIS Dataset Brain Slice Generation via VQVAE
__Student Name__
_Conal O'Leary s4583653_
## **Description**

This is my request for comments on my VQVAE Algorithm. For descriptions, results and reproducibility please see the `README.md` file contained within this PR. References have been added to the `README.md` and the `model.py` files, however, will also be included here for convenience:

### Autoregressive Models - PixelCNN

_Lopez Pinaya, da Costa and Dafflon_, 2020 - Towards Data Science, Autoregressive Models — PixelCNN - available at: https://towardsdatascience.com/autoregressive-models-pixelcnn-e30734ede0c1

### Neural Discrete Representation Learning

_Oord, Aaron van den and Vinyals, Oriol and Kavukcuoglu, Koray_, 2018 - arXiv, Neural Discrete Representation Learning - available at: https://arxiv.org/pdf/1711.00937v2.pdf

### Vector-Quantized Variational Autoencoders

_Sayak Paul_, 2021 - Keras, Vector-Quantized Variational Autoencoders - available at: https://keras.io/examples/generative/vq_vae/

### CODE REVIEW

**Comment by SiyuLiu0329** [comment]
**This is an initial inspection, no action is required at this point**
- commit messages: some could be more specific
- reconstruction: OK
- image gen: OK
- code commenting: OK
- readme: seems: OK

IMPORTANT: Commits are not in the right place. Did you create the topic-recognition branch yourself? You should fork Shakes repo in whole (there is a checkmark when you fork) and commit to his topic-recognition branch. You should be able to see work from the previous years in "recognition folder"

**Comment by scooobs** [comment]
Sorry this was a mistake I was not meant to close this PR, was trying to comment. Can you please re-open.

With regards to the forking, I forked the main branch, created my own topic recognition branch and then opened a PR to merge into Shakes topic recognition branch. I talked to my tutor inside the Prac and they said that this was a fine approach as lots of people in the prac were having issues with forking the topic recognition branch as there were unstaged changes that wouldn't go away.

**Comment by SiyuLiu0329** [comment]
Hi @scooobs, no worries. This is just an initial check. you will get a chance to fix it. Things like this happen.

**Comment by shakes76** [comment]
## Good Practice (Design/Commenting, TF/Torch Usage)
Adequate use and implementation
Good spacing and comments
Header blocks missing -1
## Recognition Problem 
Solves problem (generations a bit poor) -1
Driver Script present
File structure present
Shows Usage & Demo & Visualisation & Data usage 
Module present
Commenting
No Data leakage
Difficulty: Hard
## Commit Log
Meaningful commit messages (could be more informative) -1
Progressive commits used
## Documentation
ReadMe acceptable
Good Description and Comments 
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
No Feedback required
Request Description good

**Pull request merged**
