### PR TITLE
Mengyao Ma - 45857876 - StyleGAN-pull request test

### PR DESCRIPTION
**Pull request by MMMMMYY**
Hi，
This is my pull request. It uses the stylegan to  generated knee MRI imgaes.
The detail sees README.md

Thanks

### CODE REVIEW

**Comment by Wangxinqian** [comment]
Please do not improve the work, your work has already been very fabulous!

**Review by WeiDaiwow — COMMENTED** [review]
Have both test and driver file
Nice readme file
An algorithm solves the problems
Good design and nice implementation
Nice comments
Nice description and explanation of the algorithm
Correct pull request with the description
nice visualization and plots
Dependencies included
Nice output and plots
Nice markdown
Nice reference

Suggestions:
1. All commits happened in 4 days

**Comment by shakes76** [comment]
## TF/Torch Usage
Adequate use and implementation
## Good Practice (Design/Commenting)
Good spacing and comments
No Header blocks -1
## Algorithm 
Driver Script present
Shows Usage & Demo & Visualisation & Data usage 
Module present
No Data leakage 
Difficulty: Hard
## Commit Log
Meaningful commit messages, could be more descriptive -1
Progressive commits used
## Documentation
Good Description, but could use more comments -1
Markdown used PDF submitted
## Pull Request
Successful Pull Request (Working Algorithm Delivered on Time in Correct Branch) 
Merge conflict because of the .gitignore file, can you either remove the file or revert it so I can merge? -2
Request Description could be more informative -1

**Comment by MMMMMYY** [comment]
> sure. I will fix it.

**Comment by ShangGao-forever** [comment]
Thank you Shakes, I have deleted .gitignore file already. 从 Windows 版邮件发送 发件人: Shakes发送时间: 2021年11月21日 17:14收件人: shakes76/PatternFlow抄送: Shang Gao; Comment主题: Re: [shakes76/PatternFlow] Mengyao Ma - 45857876 - StyleGAN-pull request test (PR #226) TF/Torch UsageAdequate use and implementationGood Practice (Design/Commenting)Good spacing and commentsNo Header blocks -1AlgorithmDriver Script presentShows Usage & Demo & Visualisation & Data usageModule presentNo Data leakageDifficulty: HardCommit LogMeaningful commit messages, could be more descriptive -1Progressive commits usedDocumentationGood Description, but could use more comments -1Markdown used PDF submittedPull RequestSuccessful Pull Request (Working Algorithm Delivered on Time in Correct Branch)Merge conflict because of the .gitignore file, can you either remove the file or revert it so I can merge? -2Request Description could be more informative -1—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shakes76** [comment]
Still showing the .gitignore with conflict. Feedback was tried though, so mark awarded. Still can't merge though.

**Comment by MMMMMYY** [comment]
> Still showing the .gitignore with conflict. Feedback was tried though, so mark awarded. Still can't merge though.

I fix that right now. could you please try again?

**Pull request merged**
